/sim_node:
  ros__parameters:
    camera_resolution: 0.4
    cam_hz: 40.0
    shoot_hz: 10.0
    fov: 34.68
    lidar_enable: false
    lidar_hz: 5.5
    sim_speed: 1.0
    get_ground_truth: false
    cam_enable: true
/controller:
  ros__parameters:
    max_linear_velocity: 5.0
    max_angular_velocity: 5.0
    max_pitch_velocity: 5.0
    max_yaw_velocity: 5.0
